// priority: 0

StartupEvents.registry('item', event => {
    event.create('copper_coin')
    event.create('silver_coin')
    event.create('gold_coin')
    event.create('netherite_coin')
    event.create('item_0')
    event.create('item_1')
    event.create('item_2')
    event.create('item_3')
    event.create('item_4')
    event.create('item_5')
    event.create('item_6')
    event.create('item_7')
    event.create('item_8')
    event.create('item_9')
    event.create('item_10')
    event.create('item_11')
    event.create('item_12')
    event.create('item_13')
    event.create('item_14')
    event.create('item_15')
    event.create('item_16')
    event.create('item_17')
    event.create('item_18')
    event.create('item_19')
    event.create('item_20')
})